### ISSUE TITLE
xPubs not accepted for DOGE, LTC

### ISSUE THREAD

**Issue by sp1r0-vtsc** [Vermont-Secure-Computing/lucky-cat-terminal#17]
Using apk v1.1 created on 11/20/24

Copying and pasting the exported public keys in xPub format from Coinbase wallet results in "Invalid address" error.

We should accept valid xPubs with or without the LTC: and DOGE: prefix since the export string from Coinbase wallet contains these.

**Comment by RobertStuff** [comment]
> Using apk v1.1 created on 11/20/24
> 
> Copying and pasting the exported public keys in xPub format from Coinbase wallet results in "Invalid address" error.
> 
> We should accept valid xPubs with or without the LTC: and DOGE: prefix since the export string from Coinbase wallet contains these.

Thanks for the report. I will fix it..

**Comment by RobertStuff** [comment]
@sp1r0-vtsc Please do check the new apk.. Cheers..

**Comment by sp1r0-vtsc** [comment]
@RobertStuff Just added the xPubs for LTC and DOGE successfully.  Using the prefix is still not accepted but for the purposes of getting this out to market I don't think this is a blocker especially since this is a copy and paste operation so removing the prefix is no extra work on the part of the user.  I'm going to close this as fixed and we can add a feature enhancement later if Luke thinks it's necessary.
