### ISSUE TITLE
Monero payment timeout

### ISSUE THREAD

**Issue by sp1r0-vtsc** [Vermont-Secure-Computing/lucky-cat-terminal#24]
Sending a Monero payment is not detected by LCTerm in the 15 min timeframe.  

We should be checking for a single confirmation to register the payment.  In my testing this still took about 4-5 minutes but this seems acceptable for our purposes.  

This test was performed using Cake wallet and the transaction took about 20 minutes for the cake wallet to confirm receipt.

See screenshot for evidence :)
![monero_timeout](https://github.com/user-attachments/assets/c3f68fcb-6854-42a4-94cb-23b19d2da1a6)

**Comment by sp1r0-vtsc** [comment]
I used the updated apk and received a new error "Server Response Error..." - see attached for details.  This was using Cake wallet with the Primary address and you can see on Monero.com that the transaction was 'confirmed' after a single confirmation.  It seems we should follow their lead and detect payment on the first confirmation (if not before).
![Monero_server_error](https://github.com/user-attachments/assets/8df58100-c46d-4908-a177-dd7765eb0923)

**Comment by RobertStuff** [comment]
@sp1r0-vtsc thanks for the heads up. I will look at this error..

**Comment by sp1r0-vtsc** [comment]
@RobertStuff nice one.  Payment was detected in ~10 secs.  

Closing this as fixed.
